version: '3.7'

networks:
  bff_arch_net:

volumes:
  backend-data:

services:
  backend:
    image: nginx
    platform: linux/amd64
    volumes:
      - ./backend_nginx:/app/app/webroot
      - ./docker/backend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8000:80"
    environment:
    - NGINX_HOST=backend.com
    - NGINX_PORT=80

  bff:
    image: node:16.14.0
    volumes:
      - ./bff_exprese_graphql:/app
    ports:
    - "4000:4000"
    command: /bin/bash -c "cd /app; npm install; npm run ts-node-dev"

  front:
    image: node:16.14.0
    volumes:
      - ./front_nuxt3:/app
    ports:
    - "3000:3000"
    command: /bin/bash -c "cd /app; npm install; npm run dev -- -o"
